# Site settings
author: Justin Phillips
title: Justin is Learning
header-img: img/home-bg.png
email: justinphil02@yahoo.com
copyright_name: Justin Phillips
description: > # this means to ignore newlines until "baseurl:"
  A blog about my learning journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JustiP3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
